"""
Case Package Export.

Assembles a self-contained ZIP file for L1->L2->L3 escalation handoffs.
Contains all investigation artifacts: PDFs, Excel, SAR draft, filing worksheets,
evidence store, review session, and pipeline metadata.

Meets the 5-year retention requirement with a complete audit trail.
"""

from __future__ import annotations

import json
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any

from logger import get_logger

logger = get_logger(__name__)


def _build_readme(output: Any, included_files: list[str], missing_files: list[str]) -> str:
    """Generate a README manifest for the case package.

    Args:
        output: KYCOutput instance.
        included_files: List of filenames actually included in the ZIP.
        missing_files: List of expected filenames that were absent.
    """
    cd = output.client_data or {}
    client_name = cd.get("full_name") or cd.get("legal_name", "Unknown")

    risk_level = "N/A"
    if output.synthesis and output.synthesis.revised_risk_assessment:
        risk_level = output.synthesis.revised_risk_assessment.risk_level.value
    elif output.intake_classification and output.intake_classification.preliminary_risk:
        risk_level = output.intake_classification.preliminary_risk.risk_level.value

    decision = output.final_decision.value if output.final_decision else "PENDING"

    lines = [
        "=" * 60,
        "KYC INTELLIGENCE — CASE PACKAGE",
        "=" * 60,
        "",
        f"Client:    {client_name}",
        f"Client ID: {output.client_id}",
        f"Type:      {output.client_type.value.upper()}",
        f"Risk:      {risk_level}",
        f"Decision:  {decision}",
        f"Generated: {output.generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "PACKAGE CONTENTS:",
        "-" * 40,
    ]

    for fname in included_files:
        lines.append(f"  {fname}")

    lines.append("  README.txt                   - This file")

    if missing_files:
        lines.append("")
        lines.append("MISSING (expected but not available):")
        lines.append("-" * 40)
        for fname in missing_files:
            lines.append(f"  {fname}")

    lines.extend([
        "",
        "NOTES:",
        "- All PDFs include an executive summary page as page 1",
        "- Excel workbook contains 7 sheets: Executive Summary, Screening Results,",
        "  Risk Factors, UBO/Ownership, Decision Points, Regulatory Actions,",
        "  Evidence Detail",
        "- SAR narrative draft uses [E-XXX] citations linking to evidence records",
        "- Filing pre-fills are AUTO-GENERATED and require analyst review",
        "",
        "RETENTION:",
        "This case package is designed for the 5-year record retention",
        "requirement under FINTRAC and FinCEN regulations.",
        "",
        "Package generated by KYC Onboarding Intelligence System",
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ])
    return "\n".join(lines)


def _build_metadata(output: Any) -> dict:
    """Build pipeline metadata for the case package."""
    return {
        "client_id": output.client_id,
        "client_type": output.client_type.value,
        "schema_version": output.schema_version,
        "generated_at": output.generated_at.isoformat(),
        "duration_seconds": output.duration_seconds,
        "is_degraded": output.is_degraded,
        "pipeline_metrics": output.metrics or {},
        "investigation_plan": output.intake_classification.model_dump() if output.intake_classification else {},
        "final_decision": output.final_decision.value if output.final_decision else None,
        "package_created_at": datetime.now().isoformat(),
    }


def export_case_package(
    output: Any,
    output_dir: Path,
    evidence_store: list | None = None,
    sar_narrative: dict | None = None,
    fincen_filing: dict | None = None,
    fintrac_filing: dict | None = None,
) -> Path:
    """Assemble a case package ZIP file.

    Args:
        output: KYCOutput instance.
        output_dir: Directory where PDFs and Excel already exist (05_output/).
        evidence_store: Flat list of evidence record dicts.
        sar_narrative: Pre-generated SAR narrative dict.
        fincen_filing: Pre-generated FinCEN filing dict.
        fintrac_filing: Pre-generated FINTRAC filing dict.

    Returns:
        Path to the generated ZIP file.
    """
    client_id = output.client_id
    zip_name = f"{client_id}_case_package.zip"
    zip_path = output_dir / zip_name

    output_dir.mkdir(parents=True, exist_ok=True)

    # Track which files are actually included vs missing
    included_files: list[str] = []
    missing_files: list[str] = []

    # Expected file manifest with descriptions
    _FILE_DESCRIPTIONS = {
        "01_aml_operations_brief.pdf": "Full AML investigation (incl. executive summary page)",
        "02_risk_assessment_brief.pdf": "Quantitative risk analysis",
        "03_regulatory_actions_brief.pdf": "Regulatory filings & deadlines",
        "04_onboarding_decision_brief.pdf": "Go/no-go decision brief",
        "05_screening_results.xlsx": "Multi-sheet Excel workbook (filterable)",
        "06_sar_narrative_draft.txt": "SAR/STR narrative draft (for filing)",
        "07_sar_filing_fincen.json": "FinCEN SAR Form 111 pre-fill",
        "08_str_filing_fintrac.json": "FINTRAC STR pre-fill",
        "09_evidence_store.json": "Complete evidence records",
        "10_review_session.json": "Compliance officer review audit trail",
        "11_pipeline_metadata.json": "Pipeline timing, tokens, versions",
        "12_audit_trail.jsonl": "Structured audit trail (stage boundaries, agent outcomes, officer actions)",
    }

    def _track(zip_entry: str):
        desc = _FILE_DESCRIPTIONS.get(zip_entry, "")
        label = f"{zip_entry:<35s} - {desc}" if desc else zip_entry
        included_files.append(label)

    def _track_missing(zip_entry: str):
        desc = _FILE_DESCRIPTIONS.get(zip_entry, "")
        label = f"{zip_entry:<35s} - {desc}" if desc else zip_entry
        missing_files.append(label)

    with zipfile.ZipFile(str(zip_path), "w", zipfile.ZIP_DEFLATED) as zf:
        # PDFs
        pdf_files = [
            ("aml_operations_brief.pdf", "01_aml_operations_brief.pdf"),
            ("risk_assessment_brief.pdf", "02_risk_assessment_brief.pdf"),
            ("regulatory_actions_brief.pdf", "03_regulatory_actions_brief.pdf"),
            ("onboarding_decision_brief.pdf", "04_onboarding_decision_brief.pdf"),
        ]
        for src_name, zip_entry in pdf_files:
            src_path = output_dir / src_name
            if src_path.exists():
                zf.write(str(src_path), zip_entry)
                _track(zip_entry)
            else:
                _track_missing(zip_entry)

        # Excel workbook
        excel_path = output_dir / "screening_results.xlsx"
        if excel_path.exists():
            zf.write(str(excel_path), "05_screening_results.xlsx")
            _track("05_screening_results.xlsx")
        else:
            _track_missing("05_screening_results.xlsx")

        # SAR narrative
        if sar_narrative:
            narrative_text = sar_narrative.get("narrative_text", "")
            zf.writestr("06_sar_narrative_draft.txt", narrative_text)
            _track("06_sar_narrative_draft.txt")
        else:
            _track_missing("06_sar_narrative_draft.txt")

        # Filing pre-fills
        if fincen_filing:
            zf.writestr(
                "07_sar_filing_fincen.json",
                json.dumps(fincen_filing, indent=2, default=str),
            )
            _track("07_sar_filing_fincen.json")
        else:
            _track_missing("07_sar_filing_fincen.json")
        if fintrac_filing:
            zf.writestr(
                "08_str_filing_fintrac.json",
                json.dumps(fintrac_filing, indent=2, default=str),
            )
            _track("08_str_filing_fintrac.json")
        else:
            _track_missing("08_str_filing_fintrac.json")

        # Evidence store
        if evidence_store:
            zf.writestr(
                "09_evidence_store.json",
                json.dumps(
                    evidence_store.to_list() if hasattr(evidence_store, 'to_list') else list(evidence_store),
                    indent=2, default=str,
                ),
            )
            _track("09_evidence_store.json")
        else:
            _track_missing("09_evidence_store.json")

        # Review session
        if output.review_session:
            zf.writestr(
                "10_review_session.json",
                json.dumps(output.review_session.model_dump(), indent=2, default=str),
            )
            _track("10_review_session.json")
        else:
            _track_missing("10_review_session.json")

        # Pipeline metadata
        metadata = _build_metadata(output)
        zf.writestr(
            "11_pipeline_metadata.json",
            json.dumps(metadata, indent=2, default=str),
        )
        _track("11_pipeline_metadata.json")

        # Audit trail
        audit_path = output_dir.parent / "audit_trail.jsonl"
        if audit_path.exists():
            zf.write(str(audit_path), "12_audit_trail.jsonl")
            _track("12_audit_trail.jsonl")
        else:
            _track_missing("12_audit_trail.jsonl")

        # README (built from actual contents)
        readme = _build_readme(output, included_files, missing_files)
        zf.writestr("README.txt", readme)

    logger.info("Case package exported: %s", zip_path)
    return zip_path
